FROM node:22-alpine

ENV NODE_ENV=development
ENV HUSKY=0

RUN corepack enable && corepack prepare pnpm@latest --activate

WORKDIR /app

COPY package.json pnpm-lock.yaml pnpm-workspace.yaml ./
RUN pnpm install --frozen-lockfile

CMD ["pnpm", "start:dev"]
